language: node_js
node_js:
  - "stable"

env:
  global:
    - NODE_ENV="development"
    - RANK_TEMPLATE="./resources/templates/template.json"
    - RANK_FILE_DIR="./resources/rank_files/"
    - MAX_DELETE_MESSAGES=100
    - DELETE_MESSAGE_DELAY=3000
    - VERSION=1.1.2
    - INVITE_URL="https://discord.com/oauth2/authorize?client_id=783751587189358595&scope=bot&permissions=519232"
    - DISCORD_TOKEN=NzgzNzUxNTg3MTg5MzU4NTk1.X8fTiw._CdQIWMQFTb1FAOJhznilYY-LQQ
    - OWNER=210421780496515074
    - PREFIX=!

cache:
  directories:
    - node_modules

install: npm install
